include:
  - ./common/lvops/compose.yaml

services:
  app:
    image: ${APP_IMAGE:-}
    platform: linux/amd64
    hostname: lvbe
    build:
      context: ..
      target: ${APP_TARGET}
      dockerfile: ops/Dockerfile
      args:
        APP_GROUP_ID: ${APP_GROUP_ID:-1000}
        APP_USER_ID: ${APP_USER_ID:-1000}
    env_file:
      - ../src/.env.dev
    ports:
      - ${APP_PORT:-3001}:3000
    volumes:
      - ../src:/var/www/app
    # TODO: implement healthcheck
    # healthcheck:
    #     test: ['CMD-SHELL', 'pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
    #     interval: 30s
    #     timeout: 10s
    #     retries: 3
    #     start_period: 30s
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    user: postgres
    image: postgres:latest
    platform: linux/amd64
    hostname: lvbe-db
    ports:
      - '${DB_PORT:-5433}:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: lvbe
      POSTGRES_PASSWORD: lvbe
      POSTGRES_DB: lv
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
